Traceback (most recent call last):
  File "/home/jeb/Projects/training/regularization-using-data/train.py", line 157, in <module>
    out, accuracies_mean = jax.lax.scan(
                           ^^^^^^^^^^^^^
  File "/home/jeb/Projects/training/regularization-using-data/train.py", line 114, in training
    train_state, metrics = jax.lax.scan(
                           ^^^^^^^^^^^^^
  File "/home/jeb/Projects/training/regularization-using-data/training/training.py", line 109, in update_step
    (loss, (accuracy)), grads = jax.value_and_grad(simplified_loss, has_aux=True)(params)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeb/Projects/training/regularization-using-data/training/training.py", line 108, in <lambda>
    simplified_loss = lambda params: loss_fn(params, images, labels)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeb/Projects/training/regularization-using-data/training/training.py", line 67, in loss_fn
    accuracy = accuracy(logits, labels)
               ^^^^^^^^
UnboundLocalError: cannot access local variable 'accuracy' where it is not associated with a value
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
